variables:
  GIT_DEPTH: 1000

.base-job:
  stage: test
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

.ci-history-cache:
  cache:
    - key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
      policy: pull-push
      paths:
        - ci_ok_history

SERVICE-A-go-cache:
  image: alpine
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh


SERVICE-A-node-cache:
  image: jersou/alpine-git-nodejs-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml node-cache-version/skip.js
  script:
    - time node-cache-version/skip.js || _example/service-A/test.sh
    - time node-cache-version/skip.js || _example/service-A/test.sh
    - time node-cache-version/skip.js || _example/service-A/test.sh

SERVICE-A-bash-cache:
  image: jersou/alpine-bash-curl-git-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - time bash-cache-version/skip.sh || _example/service-A/test.sh
    - time bash-cache-version/skip.sh || _example/service-A/test.sh
    - time bash-cache-version/skip.sh || _example/service-A/test.sh


SERVICE-A-node-api:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh

SERVICE-A-go-api:
  image: alpine
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh

SERVICE-B-go-cache:
  image: alpine
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh

SERVICE-B-node-cache:
  image: jersou/alpine-git-nodejs-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml node-cache-version/skip.js
  script:
    - time node-cache-version/skip.js || _example/service-B/test.sh
    - time node-cache-version/skip.js || _example/service-B/test.sh
    - time node-cache-version/skip.js || _example/service-B/test.sh

SERVICE-B-bash-cache:
  image: jersou/alpine-bash-curl-git-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - time bash-cache-version/skip.sh || _example/service-B/test.sh
    - time bash-cache-version/skip.sh || _example/service-B/test.sh
    - time bash-cache-version/skip.sh || _example/service-B/test.sh


SERVICE-B-node-api:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh

SERVICE-B-go-api:
  image: alpine
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
