
variables:
  GIT_DEPTH: 1000


.bash-api-version-ci-history:
  stage: test
  # allow the 222 exit code : allow failure if tree is found in history
  allow_failure:
    exit_codes:
      - 222
  before_script:
    # skip the job if the SHA-1 of the "$SKIP_IF_TREE_OK_IN_PAST" tree is in the history file
    - |
      ! grep "^$(git ls-tree HEAD -- $SKIP_IF_TREE_OK_IN_PAST | tr / \| | git mktree):" .ci_ok_history \
      || exit 222
  after_script:
    # if job is successful, add the SHA-1 of the "$SKIP_IF_TREE_OK_IN_PAST" tree to the history file
    - |
      [ "$CI_JOB_STATUS" = success ] \
       && echo $(git ls-tree HEAD -- $SKIP_IF_TREE_OK_IN_PAST | tr / \| | git mktree):${CI_JOB_ID} >> .ci_ok_history
  cache:
    key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
    policy: pull-push
    untracked: true
    paths:
      - .ci_ok_history



SERVICE-A-node:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt


SERVICE-A-go:
  image: alpine
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-A-cache:
  image: jersou/alpine-git
  extends: .bash-api-version-ci-history
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml
  script:
    - _example/service-A/test.sh
    - _example/service-A/test.sh
    - _example/service-A/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-B-node:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt


SERVICE-B-go:
  image: alpine
  stage: test
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

SERVICE-B-cache:
  image: jersou/alpine-git
  extends: .bash-api-version-ci-history
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml
  script:
    - _example/service-B/test.sh
    - _example/service-B/test.sh
    - _example/service-B/test.sh
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt


