variables:
  GIT_DEPTH: 1000

go-api-version-build:
  when: manual
  stage: build
  image: golang:1.20-bullseye
  script:
    - cd go-api-version/ && apt update && apt install -y upx-ucl && ./build.sh
  artifacts:
    when: on_success
    paths:
      - go-api-version/skip-if-tree-ok-in-past

.base-job:
  stage: test
  artifacts:
    expire_in: 30 days
    paths:
      - result.txt

.ci-history-cache:
  cache:
    - key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
      policy: pull-push
      paths:
        - ci_ok_history

########################################################################################################################
SERVICE-A-go-cache:
  image: alpine
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-A/test.sh

SERVICE-B-go-cache:
  image: alpine
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-cache-version/skip-if-tree-ok-in-past || _example/service-B/test.sh

########################################################################################################################
SERVICE-A-node-cache:
  image: jersou/alpine-git-nodejs-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml node-cache-version/skip.js
  script:
    - time node-cache-version/skip.js || _example/service-A/test.sh
    - time node-cache-version/skip.js || _example/service-A/test.sh
    - time node-cache-version/skip.js || _example/service-A/test.sh

SERVICE-B-node-cache:
  image: jersou/alpine-git-nodejs-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml node-cache-version/skip.js
  script:
    - time node-cache-version/skip.js || _example/service-B/test.sh
    - time node-cache-version/skip.js || _example/service-B/test.sh
    - time node-cache-version/skip.js || _example/service-B/test.sh

########################################################################################################################
SERVICE-A-bash-cache:
  image: jersou/alpine-bash-curl-git-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - time bash-cache-version/skip.sh || _example/service-A/test.sh
    - time bash-cache-version/skip.sh || _example/service-A/test.sh
    - time bash-cache-version/skip.sh || _example/service-A/test.sh

SERVICE-B-bash-cache:
  image: jersou/alpine-bash-curl-git-unzip
  extends:
    - .base-job
    - .ci-history-cache
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - time bash-cache-version/skip.sh || _example/service-B/test.sh
    - time bash-cache-version/skip.sh || _example/service-B/test.sh
    - time bash-cache-version/skip.sh || _example/service-B/test.sh

########################################################################################################################
SERVICE-A-node-api:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh
    - time node-api-version/skip.js || _example/service-A/test.sh

SERVICE-B-node-api:
  image: jersou/alpine-bash-curl-fx-git-nodejs-unzip
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml node-api-version/skip.js
  script:
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh
    - time node-api-version/skip.js || _example/service-B/test.sh

########################################################################################################################

SERVICE-A-go-api:
  image: alpine
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-A/test.sh

SERVICE-B-go-api:
  image: alpine
  extends: .base-job
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-api-version/skip-if-tree-ok-in-past
  script:
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh
    - time go-api-version/skip-if-tree-ok-in-past || _example/service-B/test.sh

########################################################################################################################
########################################################################################################################
########################################################################################################################

.base-job-go-before-script-allow-failure-skip:
  stage: test
  cache:
    - key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
      policy: pull-push
      paths:
        - ci_ok_history
  allow_failure:
    exit_codes:
      - 222    # allow the 222 exit code : allow failure if tree is found in history
  variables:
    SKIP_CI_NO_ARTIFACT: "true"
  before_script:
    # skip the job if the SHA-1 of the "$SKIP_IF_TREE_OK_IN_PAST" tree is in the history file
    - "! time go-cache-version/skip-if-tree-ok-in-past || exit 222"

SERVICE-A-go-skip-allow-failure:
  image: alpine
  extends: .base-job-go-before-script-allow-failure-skip
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - _example/service-A/test.sh
    - _example/service-A/test.sh
    - _example/service-A/test.sh


SERVICE-B-go-skip-allow-failure:
  image: alpine
  extends: .base-job-go-before-script-allow-failure-skip
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml go-cache-version/skip-if-tree-ok-in-past
  script:
    - _example/service-B/test.sh
    - _example/service-B/test.sh
    - _example/service-B/test.sh

########################################################################################################################
########################################################################################################################
########################################################################################################################

.base-job-bash-before-script-allow-failure-skip:
  stage: test
  cache:
    - key: "${CI_PROJECT_NAMESPACE}__${CI_PROJECT_NAME}__${CI_JOB_NAME}__ci_ok_history"
      policy: pull-push
      paths:
        - ci_ok_history
  allow_failure:
    exit_codes:
      - 222    # allow the 222 exit code : allow failure if tree is found in history
  variables:
    SKIP_CI_NO_ARTIFACT: "true"
  before_script:
    # skip the job if the SHA-1 of the "$SKIP_IF_TREE_OK_IN_PAST" tree is in the history file
    - "! time bash-cache-version/skip.sh || exit 222"

SERVICE-A-bash-skip-allow-failure:
  image: jersou/alpine-bash-git-unzip
  extends: .base-job-bash-before-script-allow-failure-skip
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-A _example/LIB-1/test.sh _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - _example/service-A/test.sh
    - _example/service-A/test.sh
    - _example/service-A/test.sh


SERVICE-B-bash-skip-allow-failure:
  image: jersou/alpine-bash-git-unzip
  extends: .base-job-bash-before-script-allow-failure-skip
  variables:
    SKIP_IF_TREE_OK_IN_PAST: _example/service-B _example/LIB-2 .gitlab-ci.yml bash-cache-version/skip.sh
  script:
    - _example/service-B/test.sh
    - _example/service-B/test.sh
    - _example/service-B/test.sh
